Map<String, String> singupEn = {
  'SingupScreen1': 'Create New Account',
  'SingupScreen2': 'First Name',
  'SingupScreen2*': 'Enter your first name in English',
  'SingupScreen3': 'Last Name',
  'SingupScreen3*': 'Enter your family name in English',
  'SingupScreen4': 'Email Address',
  'SingupScreen5': 'Mobile Number',
  'SingupScreen6': 'Password',
  'SingupScreen7': 'Confirm Password',
  'SingupScreen8': 'I agree to the ',
  'SingupScreen9': 'Terms and Conditions',
  'SingupScreen10': 'Sign Up',
  'SingupController1': 'This field is required',
  'SingupController2': 'This field is required',
  'SingupController3': 'This field is required',
  'SingupController4': 'This field is required',
  'SingupController5': 'The phone number must be 9 digits',
  'SingupController6': 'This field is required',
  'SingupController7': 'Password must be at least 6 characters',
  'SingupController8': 'This field is required',
  'SingupController9': 'Password must be at least 6 characters',
  'SingupController10': 'Passwords do not match',
};
Map<String, String> singupAr = {
  'SingupScreen1': 'انشاء حساب جديد',
  'SingupScreen2': 'الاسم الأول',
  'SingupScreen2*': 'ادخل اسمك الأول بالغة العربية',
  'SingupScreen3': 'الاسم الاخير',
  'SingupScreen3*': 'ادخل اسم العائلة بالغة العربية',
  'SingupScreen4': 'البريد الإلكتروني',
  'SingupScreen5': 'رقم الجوال',
  'SingupScreen6': 'كلمة المرور',
  'SingupScreen7': 'تأكيد كلمة المرور',
  'SingupScreen8': 'أوافق على',
  'SingupScreen9': 'الشروط و الأحكام',
  'SingupScreen10': 'انشاء حساب',
  'SingupController1': 'هذاالحقل مطلوب',
  'SingupController2': 'هذاالحقل مطلوب',
  'SingupController3': 'هذاالحقل مطلوب',
  'SingupController4': 'هذاالحقل مطلوب',
  'SingupController5': 'يجب أن يتكون رقم الهاتف من 9 أرقام',
  'SingupController6': 'هذاالحقل مطلوب',
  'SingupController7': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
  'SingupController8': 'هذاالحقل مطلوب',
  'SingupController9': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
  'SingupController10': 'كلمة المرور غير متطابقة',
};
